/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SellerGuideRouteImport } from './routes/seller-guide'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as BuyerGuideRouteImport } from './routes/buyer-guide'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdRulesRouteImport } from './routes/ad-rules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as MeListingsRouteImport } from './routes/me.listings'
import { Route as MeFollowingRouteImport } from './routes/me.following'
import { Route as MeFavoritesRouteImport } from './routes/me.favorites'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as InboxAdminIdRouteImport } from './routes/inbox.admin.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerGuideRoute = SellerGuideRouteImport.update({
  id: '/seller-guide',
  path: '/seller-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerGuideRoute = BuyerGuideRouteImport.update({
  id: '/buyer-guide',
  path: '/buyer-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdRulesRoute = AdRulesRouteImport.update({
  id: '/ad-rules',
  path: '/ad-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeListingsRoute = MeListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => MeRoute,
} as any)
const MeFollowingRoute = MeFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => MeRoute,
} as any)
const MeFavoritesRoute = MeFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => MeRoute,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/inbox/$conversationId',
  path: '/inbox/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxAdminIdRoute = InboxAdminIdRouteImport.update({
  id: '/inbox/admin/$id',
  path: '/inbox/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-rules': typeof AdRulesRoute
  '/admin': typeof AdminRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/seller-guide': typeof SellerGuideRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/following': typeof MeFollowingRoute
  '/me/listings': typeof MeListingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/inbox/admin/$id': typeof InboxAdminIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-rules': typeof AdRulesRoute
  '/admin': typeof AdminRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/seller-guide': typeof SellerGuideRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/following': typeof MeFollowingRoute
  '/me/listings': typeof MeListingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/inbox': typeof InboxIndexRoute
  '/inbox/admin/$id': typeof InboxAdminIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-rules': typeof AdRulesRoute
  '/admin': typeof AdminRoute
  '/buyer-guide': typeof BuyerGuideRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/seller-guide': typeof SellerGuideRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/following': typeof MeFollowingRoute
  '/me/listings': typeof MeListingsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/inbox/': typeof InboxIndexRoute
  '/inbox/admin/$id': typeof InboxAdminIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-rules'
    | '/admin'
    | '/buyer-guide'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/sell'
    | '/seller-guide'
    | '/shipping'
    | '/terms'
    | '/inbox/$conversationId'
    | '/listing/$id'
    | '/me/favorites'
    | '/me/following'
    | '/me/listings'
    | '/profile/$userId'
    | '/inbox/'
    | '/inbox/admin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-rules'
    | '/admin'
    | '/buyer-guide'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/sell'
    | '/seller-guide'
    | '/shipping'
    | '/terms'
    | '/inbox/$conversationId'
    | '/listing/$id'
    | '/me/favorites'
    | '/me/following'
    | '/me/listings'
    | '/profile/$userId'
    | '/inbox'
    | '/inbox/admin/$id'
  id:
    | '__root__'
    | '/'
    | '/ad-rules'
    | '/admin'
    | '/buyer-guide'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/login'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/safety'
    | '/search'
    | '/sell'
    | '/seller-guide'
    | '/shipping'
    | '/terms'
    | '/inbox/$conversationId'
    | '/listing/$id'
    | '/me/favorites'
    | '/me/following'
    | '/me/listings'
    | '/profile/$userId'
    | '/inbox/'
    | '/inbox/admin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdRulesRoute: typeof AdRulesRoute
  AdminRoute: typeof AdminRoute
  BuyerGuideRoute: typeof BuyerGuideRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SellerGuideRoute: typeof SellerGuideRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  ListingIdRoute: typeof ListingIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
  InboxAdminIdRoute: typeof InboxAdminIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-guide': {
      id: '/seller-guide'
      path: '/seller-guide'
      fullPath: '/seller-guide'
      preLoaderRoute: typeof SellerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-guide': {
      id: '/buyer-guide'
      path: '/buyer-guide'
      fullPath: '/buyer-guide'
      preLoaderRoute: typeof BuyerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-rules': {
      id: '/ad-rules'
      path: '/ad-rules'
      fullPath: '/ad-rules'
      preLoaderRoute: typeof AdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/listings': {
      id: '/me/listings'
      path: '/listings'
      fullPath: '/me/listings'
      preLoaderRoute: typeof MeListingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/following': {
      id: '/me/following'
      path: '/following'
      fullPath: '/me/following'
      preLoaderRoute: typeof MeFollowingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/favorites': {
      id: '/me/favorites'
      path: '/favorites'
      fullPath: '/me/favorites'
      preLoaderRoute: typeof MeFavoritesRouteImport
      parentRoute: typeof MeRoute
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/inbox/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/admin/$id': {
      id: '/inbox/admin/$id'
      path: '/inbox/admin/$id'
      fullPath: '/inbox/admin/$id'
      preLoaderRoute: typeof InboxAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MeRouteChildren {
  MeFavoritesRoute: typeof MeFavoritesRoute
  MeFollowingRoute: typeof MeFollowingRoute
  MeListingsRoute: typeof MeListingsRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeFavoritesRoute: MeFavoritesRoute,
  MeFollowingRoute: MeFollowingRoute,
  MeListingsRoute: MeListingsRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdRulesRoute: AdRulesRoute,
  AdminRoute: AdminRoute,
  BuyerGuideRoute: BuyerGuideRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SellerGuideRoute: SellerGuideRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  InboxConversationIdRoute: InboxConversationIdRoute,
  ListingIdRoute: ListingIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  InboxIndexRoute: InboxIndexRoute,
  InboxAdminIdRoute: InboxAdminIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
