// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://uddfnxsoxxnafagxeovf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZGZueHNveHhuYWZhZ3hlb3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5OTczNDMsImV4cCI6MjA5MzU3MzM0M30.gQgJHTK85mBZGzU3KUtfwwVq2tC6anVRrDCBS5CSXU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

// Provide a SSR-safe no-op storage so the auth module never touches `localStorage`
// at module init on the server.
const memoryStorage: Storage = {
  getItem: () => null,
  setItem: () => {},
  removeItem: () => {},
  clear: () => {},
  key: () => null,
  length: 0,
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : memoryStorage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  },
});

export const isSupabaseConfigured = true;
