// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uddfnxsoxxnafagxeovf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZGZueHNveHhuYWZhZ3hlb3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5OTczNDMsImV4cCI6MjA5MzU3MzM0M30.gQgJHTK85mBZGzU3KUtfwwVq2tC6anVRrDCBS5CSXU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});